---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: flask-sample-deployment
objects:
  - apiVersion: apps/v1
    kind: Deployment
      name: "${NAME}"
    spec:
      replicas: 1
      selector:
        matchLabels:
         app: "${NAME}"
      template:
        metadata:
          labels:
            app: "${NAME}"
        spec:
          containers:
            - image: "${APP_IMAGE}@${APP_IMAGE_DIGEST}"
              name: flask-sample
parameters:
 - name: NAME
   displayName: Name
   required: true
   value: flask-sample
 - name: APP_IMAGE
   required: true
   value: image-registry.openshift-image-registry.svc:5000/sumura-work/flask-sample
 - name: APP_IMAGE_DIGEST
   displayName: Application Image digest value
   required: true
